### ISSUE TITLE
如何计算face_area

### ISSUE THREAD

**Issue by chenlexing** [Curzibn/yry#10]
请问 face_area 是怎么算出来的哈，yry的莫版图用qq 和 face++ 的人脸检测得到的都跟 yry 设置的不一致

**Comment by Curzibn** [comment]
因为是指定了模板图，所以手动设置

**Comment by chenlexing** [comment]
@Curzibn 谢谢回答！
明白是手动设置，顺序是[left,top,width,height]。
请问坐标是起始点(0,0)是左上角还是左下角哇？
宽度和高度是怎么计算的，是以什么为边界计算宽的两边的？是以什么为边界计算高的两边的？

**Comment by Curzibn** [comment]
左上角(0,0)，然后手动测量，能把模特人脸包起来就行
