### ISSUE TITLE
face area

### ISSUE THREAD

**Issue by kunguang** [Curzibn/yry#2]
这个face area 是不是限制死了

**Comment by brucewill1** [comment]
这个face area到底指的是哪个face的area啊？就不能自动给detect出来？

**Comment by keokeo** [comment]
可以用OpenCV或Dlib检测人脸获取face area

**Comment by Curzibn** [comment]
face area 是模特的脸部区域，readme 已经说明，是为了避免融合后整张图片扭曲而限制的区域。

**Comment by flyyue5** [comment]
您好，请问一下，同样用model那张图片，我的face area检测出来的是"width": 245, "top": 147, "left": 180, "height": 245，请问为什么会有这样的问题？在用自己的图片作为模版图时，按照检测出来的四个参数值进行设置会出错，请问中间是做了什么变换吗？谢谢。

**Comment by flyyue5** [comment]
请问这个area的值是怎么得到的呢？单位是pixel还是cm？因为和detecct出来的数据不一样，没有找到设置这个值的规律，麻烦您啦

**Comment by Curzibn** [comment]
face area 已经说明是现在图片融合的区域，所以只要手动圈一个模特脸部范围就行，我这边4个参数的顺序是[left, top, width, height]。单位都是 pixel 。

**Comment by flyyue5** [comment]
非常感谢，我再看一下，麻烦啦！
