### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by liliang55** [Curzibn/yry#6]
你好，如果有一张图片，里面是两个人的脸部头像，传一张图片替换第一个的脸部头像，再传一张，来替换第二张的脸部头像，请问，这样怎么操作呢，如果可以，我想定制开发一下，如果能，请留一下你的联系方式

**Comment by liliang55** [comment]
图片像这种的[https://wx.qygapp.com/tackimg.png](url)

**Comment by Curzibn** [comment]
你可以联系我的邮箱，我通过邮箱给你联系方式
